<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7MLTNC0" failures="1" tests="2" name="neoStroxTest.ValidateNeoStoxUserName2" time="42.903" errors="0" timestamp="2022-12-06T20:44:29 IST" skipped="0">
  <testcase classname="neoStroxTest.ValidateNeoStoxUserName2" name="validateaccBalance" time="21.076">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at neoStroxTest.ValidateNeoStoxUserName2.validateaccBalance(ValidateNeoStoxUserName2.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateaccBalance -->
  <system-out>
    <![CDATA[Waiting for 500ms
getting accBalance 
Account Balance is Rs.5,00,000.00
Waiting for 500ms
getting accBalance 
Account Balance is Rs.5,00,000.00
Waiting for 500ms
TAKESCREENSHOT
TCvalidateaccBalanceis fail..try again 
Waiting for 500ms
TAKESCREENSHOT]]>
  </system-out>
  <testcase classname="neoStroxTest.ValidateNeoStoxUserName2" name="validateUserName" time="21.827"/>
  <system-out>
    <![CDATA[Waiting for 1000ms
the actual string is
Actual username isshila jogdand
Reading username from property file
Waiting for 1000ms
the actual string is
Actual username isshila jogdand
Waiting for 500ms
TAKESCREENSHOT]]>
  </system-out>
</testsuite> <!-- neoStroxTest.ValidateNeoStoxUserName2 -->
